<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>expand_list</name>
   <tag></tag>
   <elementGuidId>825653a5-92d2-4a6a-8947-0745b5845f6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;listviewTablePending&quot;]/tbody/tr[2]/td/div/div/div[1]/div[2]/div[1]/div[2]/div/div/table/tbody/tr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
