<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>product_type_list_button_direct</name>
   <tag></tag>
   <elementGuidId>26976411-51e2-40aa-a8c5-92fe96c06486</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class='prio-append-tr-inner']/div/div/div[2]/div/div[2]/div/div/table/tbody/tr/td[7]/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
