<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>product_type_list_button_distributor</name>
   <tag></tag>
   <elementGuidId>4b6f1dca-99ac-42b7-8a72-8c1c3af96562</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class='prio-append-tr-inner']/div/div/div[2]/div/div[2]/div/div/table/tbody/tr/td[8]/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
