<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>catalog_active_button</name>
   <tag></tag>
   <elementGuidId>93818390-5c65-48fc-bf5c-e5f8fbe796a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;accountView&quot;]/div/div[2]/div[2]/div[1]/div[1]/div[3]/div[1]/a[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
