<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>distributor_pending_margin_listing</name>
   <tag></tag>
   <elementGuidId>9daef3a1-8c22-4f41-8d5d-e4e5bac617fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;distributorlistviewTablePending_wrapper&quot;]/table/tbody/tr/td[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
