<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>(//input[@id='listprice'])[1]</description>
   <name>Listprice</name>
   <tag></tag>
   <elementGuidId>15b3c5be-c00f-4c24-af52-c18a93bcfba5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='listprice'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
